In [1]:
import numpy as np 

In [4]:
a = [1, 2, 3]
print(a[2])
print(a[1:])

3
[2, 3]


In [5]:
b = np.array([1,2,3])
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
def printx():
    print("This is a function with the same name as a built-in function.")
    
printx()
#function in python can  be defined with out defining the return type unlike in java 

This is a function with the same name as a built-in function.


In [9]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(c.shape)

(3, 3)


In [11]:
c.ndim

2

In [12]:
c.size

9

In [14]:
c.dtype

dtype('int64')

In [25]:
x = np.array([1,"shashank",2])
print(x.dtype)
print(x[1])
print(x[0].dtype)

<U21
shashank
<U1


In [26]:
x = np.array([1,"5",2],dtype=np.float32)
print(x.dtype)
print(x[1])
print(x[0].dtype)

float32
5.0
float32


focus on one data type at a time in numpy beacuase of we mix up too many data types ata the same time then we might go back to the traditional dynamically typed python 

In [27]:
a = np.full((1,2),5)

In [28]:
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[5 5]]
(1, 2)
2
2


In [29]:
a = np.empty((2,3))

In [31]:
print(a)
#value reserved in the array created using the empty function i.e it creates and empty array 


[[1.35113356e-311 1.35126290e-311 6.95204990e-310]
 [0.00000000e+000 1.35109651e-311 7.56571288e-307]]


In [32]:
x_values = np.arange(0,100,10)
print(x_values)

[ 0 10 20 30 40 50 60 70 80 90]


In [35]:
x_values=np.linspace(0,100,10)
print(x_values)
#prints the number of values on the specified range but the values are evenly distributed 

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [42]:
print(np.nan)
print(np.inf)
k = np.nan
print(k)
print(type(k))

nan
inf
nan
<class 'float'>


In [43]:
k = np.sqrt(-1)
print(np.isnan(k))

True


C:\Users\boyas\AppData\Local\Temp\ipykernel_18904\773704945.py:1: RuntimeWarning: invalid value encountered in sqrt
  k = np.sqrt(-1)


In [53]:
#performing mathematical opertions using numpy arrays 
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1*5)
print(a1*5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]


In [57]:
print(a1 - a2)
print(a1 + a2)
print(a2-a1)

[-5 -5 -5 -5 -5]
[ 7  9 11 13 15]
[5 5 5 5 5]


NUMPY ARRAY FUNCTIONS BELOW 

In [65]:
x = np.array([1,2,3])
x =np.append(x,[4])
print(x)
x = np.insert(x,1,4)
print(x)

[1 2 3 4]
[1 4 2 3 4]


In [66]:
print(np.delete(x,1))
print(x)

[1 2 3 4]
[1 4 2 3 4]


In [69]:
print(np.sort(x))
print(x)

[1 2 3 4 4]
[1 4 2 3 4]


In [74]:
print(x.reshape(5))

[1 4 2 3 4]


In [79]:
a1 = ([1,2,3,4,5],
      [6,7,8,9,10],)
a2 = ([11,12,13,14,15],
      [16,17,18,19,20],)
a=np.concatenate((a1,a2),axis=0)
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [80]:
print(type(a))

<class 'numpy.ndarray'>


In [81]:
print(np.split(a,2,axis=0))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]


In [82]:
print(np.split(a,4,axis=0))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])]


In [83]:
print(a.min())
print(a.max())
print(a.mean())
print(a.sum())
print(a.std())
print(a.var())
print(np.median(a))

1
20
10.5
210
5.766281297335398
33.25
10.5


In [105]:
print(np.random.randint(99,10001))


3397


In [106]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [107]:
np.save('my_array.npy',a)

In [108]:
np.load('my_array.npy')

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [109]:
np.savetxt('my_array.csv',a)